[workspace]
resolver = "2"

default-members = [
    "crates/*",
]

members = [
    "crates/*",
]

[workspace.dependencies]
log = "0.4.21"
gpt = "3.1.0"
thiserror = "2.0.3"
nix = { version = "0.29.0", features = ["fs", "mount"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.8.0", features = ["v8"] }
zstd = "0.13.1"
