[package]
name = "disktester"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
disks = { path = "../disks" }
partitioning = { path = "../partitioning" }
provisioning = { path = "../provisioning" }
