[package]
name = "disk-test"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
disks = { path = "../crates/disks" }
log.workspace = true
partitioning = { path = "../crates/partitioning" }
pretty_env_logger = "0.5.0"
