[package]
name = "partitioning"
version = "0.1.0"
edition = "2021"
description = "A library for working directly with partitions"

[dependencies]
nix.workspace = true
linux-raw-sys = { workspace = true, features = ["loop_device"] }
