[package]
name = "disks"
version = "0.1.0"
description = "A library for working with disks and partitions"
edition = "2021"
rust-version.workspace = true

[dependencies]
regex = "1"
log.workspace = true
